ALTER TABLE AUTORISATION ADD (DT_RECEPTION_FORMULAIRE  DATE);
ALTER TABLE AUTORISATION ADD (AUTORISATION_OBTENUE  VARCHAR2(1));
update AUTORISATION set AUTORISATION_OBTENUE='A';
ALTER TABLE AUTORISATION MODIFY(AUTORISATION_OBTENUE  NOT NULL);